/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bgColor: "var(--color-bg)",
        textColor: "var(--color-text)",
        contentTextColor: "var(--color-content-text)",
        contentTextMuted: "var(--color-content-text-muted)",
        navBgColor: "var(--color-nav-bg)",
        brandColor: "var(--color-brand)",
        brandHover: "var(--color-brand-hover)",
        aiBgColor: "var(--color-ai-bg)",
        aiBorderColor: "var(--color-ai-border)",
        userBgColor: "var(--color-user-bg)",
        userTextColor: "var(--color-user-text)",
        borderColor: "var(--color-border)",
        chatWindowBg: "var(--color-chat-window-bg)",
        chatHeaderBg: "var(--color-chat-header)",
        inputBgColor: "var(--color-input-bg)",
        inputBorderColor: "var(--color-input-border)",
        inputFocusColor: "var(--color-input-focus)",
        shadowColor: "var(--color-shadow)",
        shadowLgColor: "var(--color-shadow-lg)",
        modalBg: "var(--color-modal-bg)",
        modalBackdrop: "var(--color-modal-backdrop)",
        textPrimary: "var(--color-text-primary)",
        textSecondary: "var(--color-text-secondary)",
        textTertiary: "var(--color-text-tertiary)",
        borderSecondary: "var(--color-border-secondary)",
        danger: "var(--color-danger)",
        dangerHover: "var(--color-danger-hover)",
        dangerDark: "var(--color-danger-dark)",
        dangerLight: "var(--color-danger-light)",
        dangerBorder: "var(--color-danger-border)",
        info: "var(--color-info)",
        infoHover: "var(--color-info-hover)",
        infoLight: "var(--color-info-light)",
        warning: "var(--color-warning)",
        warningHover: "var(--color-warning-hover)",
        success: "var(--color-success)",
        successHover: "var(--color-success-hover)",
        successLight: "var(--color-success-light)",
        successBorder: "var(--color-success-border)",
        successDark: "var(--color-success-dark)",
        hoverBg: "var(--color-hover-bg)",
        tableHeader: "var(--color-table-header)",
      },
      boxShadow: {
        custom:
          "0 4px 6px -1px var(--color-shadow), 0 2px 4px -1px var(--color-shadow)",
        "custom-lg":
          "0 10px 15px -3px var(--color-shadow-lg), 0 4px 6px -2px var(--color-shadow-lg)",
      },
    },
  },
  plugins: [],
};
